language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
script:
  - "bundle exec rake test"
bundler_args: --jobs 3 --retry 3
